export const students = [
  {
    id: 1,
    name: "Aman Sharma",
    rollNo: 101,
    department: "CSE",
    semester: 5,
    email: "aman101@gmail.com",
    marks: 89,
  },
  {
    id: 2,
    name: "Priya Verma",
    rollNo: 102,
    department: "IT",
    semester: 5,
    email: "priya102@gmail.com",
    marks: 45,
  },
  {
    id: 3,
    name: "Rahul Singh",
    rollNo: 103,
    department: "ECE",
    semester: 4,
    email: "rahul103@gmail.com",
    marks: 76,
  },
  {
    id: 4,
    name: "Sneha Patel",
    rollNo: 104,
    department: "CSE",
    semester: 6,
    email: "sneha104@gmail.com",
    marks: 92,
  },
  {
    id: 5,
    name: "Rohan Gupta",
    rollNo: 105,
    department: "ME",
    semester: 5,
    email: "rohan105@gmail.com",
    marks: 38,
  },
  {
    id: 6,
    name: "Neha Yadav",
    rollNo: 106,
    department: "IT",
    semester: 4,
    email: "neha106@gmail.com",
    marks: 67,
  },
  {
    id: 7,
    name: "Vikas Kumar",
    rollNo: 107,
    department: "ECE",
    semester: 6,
    email: "vikas107@gmail.com",
    marks: 55,
  },
  {
    id: 8,
    name: "Anjali Mishra",
    rollNo: 108,
    department: "CSE",
    semester: 5,
    email: "anjali108@gmail.com",
    marks: 97,
  },
];